### ISSUE TITLE
Symbols change to other font when changing to bold or header

### ISSUE THREAD

**Issue by Synisill** [ibarzabal/Genesys#28]
Dear ibarzabal,

i just recently stumbeled upon your EPIC work and i wish to thank you so much for what you have done!!!!!
It was my own desire to start on this project - when i incidentally found out that you have accomplished it already. I am in heaven!
I was just starting to delve into FGU, but i know the fundamentals it consists of. If i could be of any help, i would be willing to support you, my mail is synisill+gmx+de 

That aside, i found a minor bug: in the Notes section the formattedtext allows to change the font appearance. When i change a paragraph with a symbol**  in it to 
a) italic or underline - all is good
b) bold or "paragraph types -> heading" - the font seems to change to another (Noto_sans? Candara?) and the symbols become the representation of that other font set.

The bug can be reproduced easily. I added an image for further clarification. 
I would like to ask a question at this point: which keyboard layout do you use? Mine is German and i can only insert ability and threat dice (interactive mode), because they are incidentally the German Umlaut keys ö and ü on my keyboard. Usually i have to close FGU and edit the xml-files by entering the html-mask instead. ALT+[number] does not seem to work, when i push ALT (or ALT Gr) only the chat mode changes. 

**My definition for symbol= the icons that represent the Genesys dice (&#241; to &#255;)

![boldsymbol](https://user-images.githubusercontent.com/48999796/96017685-967bda00-0e4a-11eb-99ab-01e0596279d7.png)

**Comment by ibarzabal** [comment]
Yeah I will do a complete review in the fonts and that code for dice symbols soon after I am done with creating the vehicle system

**Comment by Synisill** [comment]
Hello again! 
I was able to solve this problem. Just take a look at the last post in my thread in the forum: https://www.fantasygrounds.com/forums/showthread.php?62826-(FGU)-Problem-with-replacing-characters-in-a-stringfield

**Comment by ibarzabal** [comment]
Hey Synisill, I fixed this in my current build.
I will upload sometime tomorrow I think
You will be able to check what I did looking at the file: manager_string_genesys.lua

I have two different functions: one for formattedtext, and another for simpletext
